
FROM ubuntu

RUN apt-get update

#RUN apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN apt-get -y install docker.io

RUN apt-get -y install maven

RUN apt-get clean
